import {
  Circle, Milk, Carrot, Apple, ShoppingBasket, ShoppingBag, Package, ShoppingCart,
  Shirt, Footprints, Watch, Sparkles, Scissors, Smartphone, Laptop, Cable, Plug,
  WashingMachine, Cpu, Home, SprayCan, UtensilsCrossed, Sofa, Lamp, PlugZap, Wrench,
  Car, Fuel, BatteryCharging, CarTaxiFront, Bus, TrainFront, ParkingCircle, RectangleHorizontal,
  Pill, Stethoscope, Cross, Smile, TestTube, Dumbbell, Heart, Palette, Ellipsis,
  Clapperboard, Tv, Gamepad2, Ticket, Utensils, Zap, Flame, Droplets, Wifi, SatelliteDish,
  Banknote, CreditCard, Building2, Wallet, MoreHorizontal, QrCode, Receipt, CircleDot,
  GlassWater, Square, Cookie, Croissant, Drumstick, Megaphone, MapPin, Phone,
  // Expanded picker set (spec item: richer icon/color choice) — distinct new glyphs only,
  // no re-aliasing of icons already imported above.
  Coffee, Fish, Beef, IceCream, Cake, Baby, Dog, Cat, Gift, BookOpen,
  GraduationCap, Briefcase, Plane, Bed, Umbrella, Sun, Cloud, Music, Camera,
  PawPrint, TreePine, Leaf, PiggyBank, HandCoins, Landmark, School, Church,
  Factory, Store, Truck, Bike, Popcorn, Pizza, Salad, Wine, Beer, Cigarette,
  Glasses, Headphones, Film, Trophy, Anchor, Tent, Mountain, Waves,
  Snowflake, Thermometer, Syringe, Users, User, UserPlus, Gem, Backpack, Key,
  Lock, ShieldCheck, Recycle, Trash2, Hammer, Ruler, Building,
  Warehouse, Bird, Rabbit, Flower2, Sprout,
  type LucideIcon,
} from "lucide-react";

/**
 * Category/merchant `icon` values are plain strings stored in Postgres (spec
 * section 13/15: `categories.icon text`), matched here to a small, fixed set of
 * Lucide icons. Unknown values fall back to `Circle` rather than crashing.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  circle: Circle,
  "circle-dot": CircleDot,
  milk: Milk,
  "glass-water": GlassWater,
  square: Square,
  carrot: Carrot,
  apple: Apple,
  "shopping-basket": ShoppingBasket,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  package: Package,
  cookie: Cookie,
  "cup-soda": GlassWater,
  croissant: Croissant,
  drumstick: Drumstick,
  ellipsis: Ellipsis,
  shirt: Shirt,
  footprints: Footprints,
  watch: Watch,
  sparkles: Sparkles,
  scissors: Scissors,
  smartphone: Smartphone,
  laptop: Laptop,
  cable: Cable,
  plug: Plug,
  "washing-machine": WashingMachine,
  cpu: Cpu,
  home: Home,
  "spray-can": SprayCan,
  "utensils-crossed": UtensilsCrossed,
  sofa: Sofa,
  lamp: Lamp,
  "plug-zap": PlugZap,
  wrench: Wrench,
  car: Car,
  fuel: Fuel,
  "battery-charging": BatteryCharging,
  "car-taxi-front": CarTaxiFront,
  bus: Bus,
  "train-front": TrainFront,
  "parking-circle": ParkingCircle,
  road: RectangleHorizontal,
  pill: Pill,
  stethoscope: Stethoscope,
  cross: Cross,
  smile: Smile,
  "test-tube": TestTube,
  dumbbell: Dumbbell,
  heart: Heart,
  "heart-pulse": Heart,
  palette: Palette,
  clapperboard: Clapperboard,
  tv: Tv,
  "gamepad-2": Gamepad2,
  ticket: Ticket,
  utensils: Utensils,
  zap: Zap,
  flame: Flame,
  droplets: Droplets,
  wifi: Wifi,
  "satellite-dish": SatelliteDish,
  banknote: Banknote,
  "credit-card": CreditCard,
  "building-2": Building2,
  wallet: Wallet,
  "more-horizontal": MoreHorizontal,
  "qr-code": QrCode,
  receipt: Receipt,
  megaphone: Megaphone,
  "map-pin": MapPin,
  phone: Phone,
  user: User,
  // Expanded picker set
  coffee: Coffee,
  fish: Fish,
  beef: Beef,
  "ice-cream": IceCream,
  cake: Cake,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  gift: Gift,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  plane: Plane,
  bed: Bed,
  umbrella: Umbrella,
  sun: Sun,
  cloud: Cloud,
  music: Music,
  camera: Camera,
  "paw-print": PawPrint,
  "tree-pine": TreePine,
  leaf: Leaf,
  "piggy-bank": PiggyBank,
  "hand-coins": HandCoins,
  landmark: Landmark,
  school: School,
  church: Church,
  factory: Factory,
  store: Store,
  truck: Truck,
  bike: Bike,
  popcorn: Popcorn,
  pizza: Pizza,
  salad: Salad,
  wine: Wine,
  beer: Beer,
  cigarette: Cigarette,
  glasses: Glasses,
  headphones: Headphones,
  film: Film,
  trophy: Trophy,
  anchor: Anchor,
  tent: Tent,
  mountain: Mountain,
  waves: Waves,
  snowflake: Snowflake,
  thermometer: Thermometer,
  syringe: Syringe,
  users: Users,
  "user-plus": UserPlus,
  gem: Gem,
  backpack: Backpack,
  key: Key,
  lock: Lock,
  "shield-check": ShieldCheck,
  recycle: Recycle,
  "trash-2": Trash2,
  hammer: Hammer,
  ruler: Ruler,
  building: Building,
  warehouse: Warehouse,
  bird: Bird,
  rabbit: Rabbit,
  "flower-2": Flower2,
  sprout: Sprout,
};

export function getIcon(name: string | null | undefined): LucideIcon {
  if (!name) return Circle;
  return ICON_MAP[name] ?? Circle;
}

/** Palette of category colors -> Tailwind-friendly bg/text pairs (spec styling guide section 16). */
export const COLOR_SWATCHES: Record<string, { bg: string; fg: string }> = {
  green: { bg: "#e7f5ec", fg: "#087f6e" },
  emerald: { bg: "#d1fae5", fg: "#047857" },
  lime: { bg: "#ecfccb", fg: "#4d7c0f" },
  pink: { bg: "#fce7f3", fg: "#db2777" },
  rose: { bg: "#ffe4e6", fg: "#e11d48" },
  fuchsia: { bg: "#fae8ff", fg: "#a21caf" },
  purple: { bg: "#f3e8ff", fg: "#9333ea" },
  violet: { bg: "#ede9fe", fg: "#6d28d9" },
  blue: { bg: "#dbeafe", fg: "#2563eb" },
  sky: { bg: "#e0f2fe", fg: "#0284c7" },
  cyan: { bg: "#cffafe", fg: "#0e7490" },
  amber: { bg: "#fef3c7", fg: "#b45309" },
  yellow: { bg: "#fef9c3", fg: "#a16207" },
  orange: { bg: "#ffedd5", fg: "#c2410c" },
  red: { bg: "#fee2e2", fg: "#dc2626" },
  teal: { bg: "#ccfbf1", fg: "#0f766e" },
  indigo: { bg: "#e0e7ff", fg: "#4338ca" },
  brown: { bg: "#f1e4d6", fg: "#92400e" },
  stone: { bg: "#f5f5f4", fg: "#57534e" },
  slate: { bg: "#f1f5f9", fg: "#475569" },
  gray: { bg: "#f3f4f6", fg: "#4b5563" },
  neutral: { bg: "#f1f5f4", fg: "#64748b" },
};

export function colorSwatch(name: string | null | undefined) {
  return COLOR_SWATCHES[name ?? "neutral"] ?? COLOR_SWATCHES.neutral;
}

export const ICON_PICKER_OPTIONS = Object.keys(ICON_MAP);
export const COLOR_PICKER_OPTIONS = Object.keys(COLOR_SWATCHES);

export function CategoryIcon({ icon, color, className }: { icon?: string | null; color?: string | null; className?: string }) {
  const Icon = getIcon(icon);
  const swatch = colorSwatch(color);
  return (
    <span
      className={className ?? "flex h-10 w-10 shrink-0 items-center justify-center rounded-xl"}
      style={{ backgroundColor: swatch.bg, color: swatch.fg }}
    >
      {/* eslint-disable-next-line react-hooks/static-components -- Icon is a stable reference picked from ICON_MAP, not created here */}
      <Icon className="h-5 w-5" />
    </span>
  );
}
